name: Build
on:
  push:
    branches: [ master, main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          # Android 8.0, API Level 26
          cmdline-tools-version: 9123335

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Create keystore file
        run: |
          keytool -genkeypair -keystore ${{ github.workspace }}/keystore.jks -keyalg RSA \
                  -keysize 2048 -validity 10000 -alias ${{ secrets.KEY_ALIAS }} -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
                  -dname "${{ secrets.Name }}"

      - name: Build Default Flavor
        run: ./gradlew build --no-daemon
        env:
          SESSION_STORE_FILE: ${{ github.workspace }}/keystore.jks
          SESSION_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SESSION_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SESSION_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Build Huawei Flavor
        run: ./gradlew assembleHuaweiDebug --no-daemon -Phuawei
        env:
          SESSION_STORE_FILE: ${{ github.workspace }}/keystore.jks
          SESSION_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SESSION_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SESSION_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: app/build/reports
